function getRandomArbitrary(min, max) {
    return Math.random() * (max - min) + min;
}

function changeP() {
    let frsthlf = ["A cavalo dado", "A mentira", "À noite", "A ocasião", "A pensar", "A pressa", "A união", "A voz do povo", "Água mole em pedra dura", "Águas passadas", "Amigos amigos", "Antes tarde", "Apressado", "Aqui se faz", "Árvore que nasce torta", "As aparências", "Batatinha quando nasce", "Cachorro que late", "Cada cabeça", "Casa de ferreiro", "De grão em grão", "Desgraça pouco", "Deus ajuda", "Deus escreve certo", "Devagar com o andor", "Devagar", "Dizei-me com quem andas", "É melhor não cutucar a onça", "É melhor prevenir", "Em boca fechada", "Em rio que tem piranha", "Em terra de cego", "Entre marido e mulher", "Filho de peixe", "Gato escaldado", "Ladrão que rouba ladrão", "Macaco velho", "Mais vale um pássaro", "Melhor prevenir", "Nada como um dia", "Não adianta chorar", "Não deixes para amanhã", "Não há bem que sempre dure", "Não se faz uma omelete", "Nem tanto ao mar", "Nem tudo que reluz", "Nem tudo", "O barato", "O bom filho", "O pior cego", "O prometido", "O que não mata", "O que os olhos não veem", "O seguro", "Olho por olho", "Onde há fumaça", "Os últimos", "Para baixo", "Para bom entendedor", "Pela boca", "Quando a esmola é muita", "Quando um burro fala", "Quando um não quer", "Quanto mais alto", "Quem avisa", "Quem cala", "Quem canta seus males", "Quem casa", "Quem com ferro fere", "Quem conta um conto", "Quem desdenha", "Quem é vivo", "Quem espera", "Quem fala o que quer", "Quem feio ama", "Quem não arrisca", "Quem não chora", "Quem não tem cão", "Quem nunca comeu melado", "Quem parte e reparte e não fica com a melhor parte", "Quem procura", "Quem ri por último", "Quem sai aos seus", "Quem semeia ventos", "Quem tem boca", "Quem tudo quer", "Quem vai ao vento", "Quem vê cara", "Rapadura é doce", "Saco vazio", "Santo da casa", "Se conselho fosse bom ninguém dava", "Se Maomé não vai à montanha", "Tudo tem solução", "Um gesto", "Um homem prevenido", "Vão-se os anéis", "Vingança"];
    let scndhlf = [" não se olham os dentes.", " tem perna curta.", " todos os gatos são pardos.", " faz o ladrão.", " morreu um burro.", " é inimiga da perfeição.", " faz a força.", " é voz de Deus.", " tanto bate até que fura.", " não movem moinhos.", " negócios à parte.", " do que nunca.", " come cru.", " aqui se paga.", " morre torta.", " enganam.", " se esparrama pelo chão.", " não morde.", " uma sentença.", " espeto de pau.", " a galinha enche o papo.", " é bobagem.", " quem cedo madruga.", " por linhas tortas.", " que o santo é de barro.", " se vai ao longe.", " e eu te direi quem és.", " com vara curta.", " do que remediar.", " não entra mosca.", " jacaré nada de costas.", " quem tem um olho é rei.", " não se mete a colher.", " peixinho é.", " tem medo de água fria.", " tem cem anos de perdão.", " não pula em galho seco.", " na mão do que dois voando.", " que remediar.", " depois do outro.", " sobre o leite derramado.", " o que podes fazer hoje.", " nem mal que nunca se acabe.", " sem quebrar os ovos.", " nem tanto à terra.", " é ouro.", " são flores.", " sai caro.", " à casa torna.", " é o que não quer ver.", " é devido.", " engorda.", " o coração não sente.", " dente por dente.", " há fogo.", " serão os primeiros.", " todo Santo ajuda.", " meia palavra basta.", " morre o peixe.", " o santo desconfia.", " o outro baixa as orelhas.", " dois não brigam.", " maior a queda.", " amigo é.", " consente.", " espanta.", " quer casa.", " com ferro será ferido.", " aumenta um ponto.", " quer comprar.", " sempre aparece.", " sempre alcança.", " escuta o que não quer.", " bonito lhe parece.", " não petisca.", " caça com gato.", " quando come se lambuza.", " ou é tolo ou não sabe da arte.", " acha.", " ri melhor.", " não degenera.", " colhe tempestades.", " vai a Roma.", " tudo perde.", " perde o assento.", " não vê coração.", " mas não é mole.", " não fica de pé.", " não faz milagre.", " vendia.", " vai a montanha a Maomé.", " menos a morte.", " vale mais que mil palavras.", " vale por dois.", " ficam os dedos.", " é um prato que se come frio."];
    let l = frsthlf.length
    let n = Math.floor(getRandomArbitrary(0, l))
    let m = Math.floor(getRandomArbitrary(0, l))
    while (m == n) {
        m = Math.floor(getRandomArbitrary(0, l))
    }
    let newtext = frsthlf[n] + scndhlf[m];
    document.getElementById("textooo").innerHTML = newtext;
}